spring.datasource.url=jdbc:postgresql://localhost:5432/gym_management
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# vnpay.tmn-code=YOUR_TMN_CODE
# vnpay.hash-secret=YOUR_HASH_SECRET
# vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# vnpay.return-url=http://localhost:8081/api/payment/vnpay/callback
# vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

server.port=8081